version: '3.7'
services:
  docker-sshd:
    hostname: docker-sshd
    build:
      context: ./sshd
      dockerfile: Dockerfile
    image: docker-sshd
    container_name: docker-sshd
    restart: always
    ports:
      - "2222:22"
    environment:    
      - ROOT_PASSWORD=password1234
    logging:
      driver: "splunk"
      options:
        splunk-token: "3f066d2a-c871-4800-87fc-e6be5fa69f1b"
        splunk-url: "https://127.0.0.1:8088"
        splunk-insecureskipverify: "true"
        splunk-format: "raw"
  docker-nmap:
    hostname: docker-nmap
    build: 
      context: ./nmap
      dockerfile: Dockerfile
    image: docker-nmap
    #command: /usr/bin/nmap --script=mysql-brute.nse 10.145.89.1
    container_name: docker-nmap
    restart: "no"